id: 335bf84842ac45c4bc75229a21b61304
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_142-The_Dharani_Entering_into_Non-conceptuality-v2
  language: bo
  author: ''
  volume: {}
